name: Valuable Leadership™
favicon: null
layout_spectrum: 0.88168
typography_spectrum: 0.82412
title: 'Master the Art & Science of Leadership™'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#565656'
    - '#c9c9c9'
    - '#969696'
  brandStrength: 0.5195140889845788
  lightness: 0.625680621014908
  saturation: 0.9980216987896711
  rhythmicContrast: 0.40704970294609666
purpose: []
